#!/usr/bin/env bash

# updating packages
sudo apt-get update

# install nginx
sudo apt-get -y install nginx

# nginx must listen to port 80 by using ufw-uncomplicated firewall
# nginx http corresponds to port 80 which is default port for http traffic
sudo ufw allow 'Nginx HTTP'

# display hello world, tee comand writes and displays output
sudo echo "Hello, world!" > /var/www/html/index.nginx-debian.html

# restart nginx without using systemct1
sudo nginx start
#sudo service nginx restart