#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

# Update the package list and install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

sudo sed -i "/http {/a\        add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
