#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01(load balancer) server

# update packages
sudo apt-get -y update

# getting latest release using PPA and install haproxy
sudo apt-get -y install software-properties-common
sudo add-apt repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y install haproxy

# Distribute requests using a roundrobin algorithm
echo '
frontend haproxy_balancer
        bind *:80
        mode http
        default_backend webservers

backend webservers
        balance roundrobin
        server 320441-web-01 54.90.12.230:80 check
        server 320441-web-02 52.86.29.154:80 check
' >> /etc/haproxy/haproxy.cfg

# restart for changes to appear
sudo service haproxy restart
