#!/usr/bin/env bash
# Create a symbolic link to enable the default Nginx site configuration
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
