#!/usr/bin/env bash
# pkill terminates process based on their names and other attributes
# -f  allows it to match against the entire command line of processes
# 4-to_infinity_and_beyond is string pattern that pkill uses to search for process
pkill  -f 4-to_infinity_and_beyond
