#!/usr/bin/env bash
# displays To infinity and beyond indefinitely.
# trap handles signals, sets up trap to catch SIGTERM signal
# trap 'command' signal, prints i am invinciple before exiting
while((1))
do
        echo "To infinity and beyond"
        sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
