#!/usr/bin/env bash
# using  Apache log access files.
# write a script that displays: visitor IP along with the HTTP status code
# must use awk
# first field 1 is visitor ip, 9th field id http status code
awk '{print $1, $9}' apache-access.log
