#!/usr/bin/env bash
# uses case statement to
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

i=1
while((i <= 20))
do
	case $i in
		4)
			echo "$i"
			echo "bad luck from China"
			;; # indicates end of a pattern or a case
		9)
			echo "$i"
			echo "bad luck from Japan"
			;;
		17)
			echo "$i"
			echo "bad luck from Italy"
			;;
		*) #default case
			echo "$i"
			;;
	esac # closes the whole case statement, shows the end
	((i++))
done
