#!/usr/bin/env bash
# displays the contents of current directory in list format
# only the part of the name after the first dash is displayed
# loop all the files in the current directory

list=$(ls) # stores the output of ls in list
for i in $list
do
	# cuts the - and selects the second field f2
	echo "$i" | cut -d '-' -f2
done
