#!/usr/bin/env bash
# This script gives information about the school file

if [ -e "school" ] # -e checks if file exists
then
	echo "school file exists"

	if [ -s "school" ] # -s checks if file is not empty
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "school" ] # checks if file is a reqular file
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
