#!/usr/bin/env bash
# compares two numbers, and then prints the smallest number.

echo "Enter num1: "
read num1
echo "Enter num2: "
read num2

if ((num1 < num2))
then
	echo "$num1 is smaller than $num2"
else
	echo "$num2 is smaller than $num1"
fi
