#!/usr/bin/env bash
# This displays all acive IPv4 addresses it’s executed on.
# ifconfig display information about the network interfaces on a Unix
# inet is the pattern that shows ipv4 addresses in the output of ifconfig
# awk '{print $2}' is used to extract second field
ifconfig | grep 'inet ' | awk '{print $2}'
