#!/usr/bin/env bash
# script that creates an RSA key pair.
# -b for bytes, -t type of key = rsa, -N specifies passphrase
# -p removing or changing passphrase, -f path to the file
ssh-keygen -t rsa -b 4096 -N betty -f school
